# Generated by Django 6.0.1 on 2026-04-17 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_references',
            new_name='payment_reference',
        ),
    ]
