# Generated by Django 6.0.1 on 2026-05-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sender_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
